#################################################################################
# See LICENSE.md for full license information.                                  #
# Software: Drasil Blockchain Application Framework                             #
# License: Drasil Source Available License v1.0                                 #
# Licensors: Torben Poguntke (torben@drasil.io) & Zak Bassey (zak@drasil.io)    #
#################################################################################
[workspace]
members = [
    "freki",
    "frigg",
    "geri",
    "gungnir",
    "heimdallr",
    "hugin",
    "mimir",
    "murin",
    "odin",
    "sleipnir",
    "vidar",
    "utxopti",
    "pauther",
    "dvltath",
]
