apiVersion: v1
kind: ConfigMap
metadata:
  name: drasil-config
data:
# Vault Unix Socket Path to communicate with Odin / Frigg
  DVLTATH_DVLTATH_VSOCKET_PATH: /cache/req.sock
# Vault Unix Secret Path to store the temporary secret
  DVLTATH_DVLTATH_SPATH: /cache/sec
# Vault KV Store
  VAULT_MOUNT: secret
# Vault Namespace
  VAULT_NAMESPACE: ""
# Vault KV-storage path
  VAULT_PATH: "drasil/"
# Vault Address
  VAULT_ADDRESSESS: http://34.118.225.4:8200
# General Pod Host IP
  POD_HOST: "0.0.0.0"
# Rust Log Level
  RUST_LOG: "debug"
  RUST_BACKTRACE: "full"
# Keys for the JWT API tokens
  JWT_PUB_KEY: '-----BEGIN PUBLIC KEY-----MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMMkapa1mVNQtUdWP9B61OpMcuBHmw+LwS66RkRJ3gYlrXCisZwWaNQo3nkNjRujIVVI9jEGCWYRdECga9lUjrg==-----END PUBLIC KEY-----'
  JWT_KEY: '-----BEGIN PRIVATE KEY-----MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgoC2z4jAczA6AkVwgoglFOd16hEIwGFAvTxxxssEYvGahRANCAAQwyRqlrWZU1C1R1Y/0HrU6kxy4EebD4vBLrpGREneBiWtcKKxnBZo1CjeeQ2NG6MhVUj2MQYJZhF0QKBr2VSOu-----END PRIVATE KEY-----'
# Reward Database Connection String
  REWARDS_DB_URL: postgres://wm_rw_dbuser:password@34.147.214.161:5432/rewarddb?password=fgMGtznfIs1OZzL
# System / Plattform Database Connection String
  PLATFORM_DB_URL: postgres://wm_rw_dbuser:password@34.147.214.161:5432/drasildb?password=fgMGtznfIs1OZzL
# DBSync Database Connection String
  DBSYNC_DB_URL: postgres://wm_ro_dbuser:dbsyncwmro#1@34.142.44.177/testnet
# Keys for Redis Pending Tx Store
  PENDING_TX_DATASTORE_1: pendingtx1
  PENDING_TX_DATASTORE_2: pendingtx2
  PENDING_TX_DATASTORE_3: pendingtx3
# Keys for Redis Pending UTxO Store
  USED_UTXO_DATASTORE_1: usedutxos1
  USED_UTXO_DATASTORE_2: usedutxos2
  USED_UTXO_DATASTORE_3: usedutxos3
# URLs to Cardano Submit APII
  CARDANO_TX_SUBMIT_ENDPOINT1: http://34.142.44.177:8090/api/submit/tx
  CARDANO_TX_SUBMIT_ENDPOINT2: ""
  CARDANO_TX_SUBMIT_ENDPOINT3: ""
# Rabbit MQ 
  AMQP_ADDR: amqp://rmq:rmq@34.118.227.181:5672
  JOB_JOB_QUEUE_NAME: drasil_jobs
# Odin URL
  ODIN_URL: 34.118.237.45:6142
# For future use 
  TXGSET: ""
# Defines the Administrator User, the user must exists and have Admin Role to be valid
  ADM_USER: "0"
# Standard Redis DB 
  REDIS_DB: redis://34.118.225.230:6379/0
# Redis DB for Pending UTxO Storage
  REDIS_DB_URL_UTXOMIND: redis://34.118.225.230:6379/0
# Reserved for future use
  REDIS_DB_URL_REPLICA: redis://34.118.225.230:6379/1
# Defines if Redis is running as Cluster or in standalone mode
  REDIS_CLUSTER: "false"





