[package]
name = "vidar"
version = "0.1.0"
edition = "2021"
description = "Drasil Blockchain Application Framework - Reward Information API"
repository = "https://github.com/Sbcdn/vidar.git"
homepage = "https://www.drasil.io"
documentation = "https://docs.drasil.io"
license = "https://github.com/Sbcdn/drasil/blob/main/LICENSE.md"
readme = "https://github.com/Sbcdn/drasil/blob/main/README.md"
authors = ["Torben Poguntke <torben@drasil.io>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { workspace = true }
bytes = "1"
pretty_env_logger = "0.4.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
cardano-serialization-lib = "11.0.5"
hex = "0.4"
jsonwebtoken = {workspace = true }
thiserror = "1.0.32"

drasil-gungnir = { path = "../../drasil-gungnir", version = "0.1.0" }
drasil-hugin = { path = "../../drasil-hugin", version = "0.1.0" }
drasil-mimir = { path = "../../drasil-mimir", version = "0.1.0" }
drasil-murin = { path = "../../drasil-murin", version = "0.1.0" }
