[package]
name = "vidar"
version = "0.1.0"
edition = "2021"
description = "Drasil Blockchain Application Framework - Reward Information API"
repository = "https://github.com/Sbcdn/vidar.git"
homepage = "https://www.drasil.io"
documentation = "https://docs.drasil.io"
license = "LICENSE.md"
readme = "README.md"
authors = ["Torben Poguntke <torben@drasil.io>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }
bytes = "1"
pretty_env_logger = "0.4.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
cardano-serialization-lib = "11.0.5"
hex = "0.4"
jsonwebtoken = { version = "8.1.0", features = ["use_pem"] }
thiserror = "1.0.32"

gungnir = { path = "../../libs/gungnir", version = "0.1.0" }
hugin = { path = "../../libs/hugin", version = "0.1.0" }
mimir = { path = "../../libs/mimir", version = "0.1.0" }
murin = { path = "../../libs/murin", version = "0.1.0" }
