FROM europe-west6-docker.pkg.dev/maestro-org-development/dapp-developer-platform-base/rust:1.61.0 as maestro-rust-base

FROM maestro-rust-base as builder
WORKDIR /heimdallr-build
ENV CARGO_HOME=/heimdallr-build/.cargo
COPY ./Cargo.toml ./Cargo.lock ./                       
COPY ./.cargo/config $CARGO_HOME/config
COPY ./.cargo/git $CARGO_HOME/git
COPY ./src ./src
RUN cargo build --release --target x86_64-unknown-linux-gnu

FROM maestro-rust-base as heimdallr
COPY --from=builder /heimdallr-build/target/x86_64-unknown-linux-gnu/release/heimdallr /usr/bin

EXPOSE 4000

CMD [ "heimdallr" ]

