apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: drasil-heimdallr
  name: heimdallr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-heimdallr
  template:
    metadata:
      labels:
        app: drasil-heimdallr
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: drasil-config
        image: docker.io/minikube/heimdallr:v1.3
        imagePullPolicy: Never
        name: heimdallr