apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigg-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigg
  labels:
    app: drasil-frigg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-frigg
  template:
    metadata:
      labels:
        app: drasil-frigg
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: frigg-storage
      containers:
      - name: frigg
        image: docker.io/minikube/frigg:v1.3
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-frigg-config
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - name: dvltath
        image: docker.io/minikube/dvltath:v1.3
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-dvltath-config
        securityContext:
          runAsUser: 1000
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /cache
          name: cache-volume