apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-worker-loki
  name: worker-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-worker-loki
  template:
    metadata:
      labels:
        app: drasil-worker-loki
    spec:
      containers:
      - env:
        - name: CONSUMER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: drasil-config
        image: docker.io/minikube/work-loki:v1.3
        imagePullPolicy: Never
        name: worker-loki