apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-geri
  name: geri
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-geri
  template:
    metadata:
      labels:
        app: drasil-geri
    spec:
      containers:
      - name: geri 
        envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-geri-config
        image: docker.io/minikube/geri:v1.3
        imagePullPolicy: Never
        