apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: drasil-heimdallr
  name: heimdallr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-heimdallr
  template:
    metadata:
      labels:
        app: drasil-heimdallr
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: drasil-config
        image: k3d-drasil-registry.localhost:12345/heimdallr:v1.3
        imagePullPolicy: IfNotPresent
        name: heimdallr
---
# Heimdallr Service
apiVersion: v1
kind: Service
metadata:
  name: drasil-heimdallr-service
spec:
  selector:
    app: drasil-heimdallr
  type: LoadBalancer
  ports:
    - port: 4000
      nodePort: 30000
      protocol: TCP
      targetPort: 4000