apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-drasil-job-processor
  name: drasil-job-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-drasil-job-processor
  template:
    metadata:
      labels:
        app: drasil-drasil-job-processor
    spec:
      containers:Hi Enrique,
      - env:
        - name: AMQP_ADDR
          value: ***REMOVED***
        - name: RUST_LOG
          value: debug
        - name: CONSUMER_NAME
          valueFrom:
            configMapKeyRef:
              key: CONSUMER_NAME
              name: preview-testnet-drasil-job-processor-config-1zhm
        - name: QUEUE_NAME
          value: drasil_jobs
        - name: REWARDS_DB_URL
          value: postgres://***REMOVED***:password@***REMOVED***/rewarddb?password=***REMOVED***
        - name: PLATFORM_DB_URL
          value: postgres://***REMOVED***:password@***REMOVED***/drasildb?password=***REMOVED***
        - name: DBSYNC_DB_URL
          value: postgres://***REMOVED***:***REMOVED***@***REMOVED***/testnet
        image: docker.io/minikube/drasil-jobs:v1.3
        imagePullPolicy: Never
        name: drasil-jobs