apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-vidar
  name: vidar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-vidar
  template:
    metadata:
      labels:
        app: drasil-vidar
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: drasil-config
        image: k3d-drasil-registry.localhost:12345/vidar:v1.3
        imagePullPolicy: IfNotPresent
        name: vidar
---
# Vidar Service
apiVersion: v1
kind: Service
metadata:
  name: drasil-vidar-service
spec:
  selector:
    app: drasil-vidar
  type: LoadBalancer
  ports:
    - port: 4001
      nodePort: 30001
      protocol: TCP
      targetPort: 4101