apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odin-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin
  labels:
    app: drasil-odin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-odin
  template:
    metadata:
      labels:
        app: drasil-odin
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: odin-storage
      containers:
        - name: dvltath
          envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-dvltath-config
          image: docker.io/minikube/dvltath:v1.3
          imagePullPolicy: Never
          resources:
            limits:
                cpu: 50m
                memory: 100Mi
            requests:
                cpu: 25m
                memory: 10Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
          volumeMounts:
          - mountPath: /cache
            name: cache-volume
        - name: odin
          imagePullPolicy: Never
          image: docker.io/minikube/odin:v1.3
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
          resources:
            limits:
                cpu: 50m
                memory: 100Mi
            requests:
                cpu: 25m
                memory: 10Mi
          envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-odin-config
