apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-worker-loki
  name: worker-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-worker-loki
  template:
    metadata:
      labels:
        app: drasil-worker-loki
    spec:
      containers:
      - env:
        - name: CONSUMER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: drasil-config
        image: k3d-drasil-registry.localhost:12345/work-loki:v1.3
        imagePullPolicy: IfNotPresent
        name: worker-loki
---
# Worker Loki Service
apiVersion: v1
kind: Service
metadata:
  name: drasil-worker-loki-service
spec:
  selector:
    app: drasil-worker-loki
  type: ClusterIP
  ports:
    - port: 4004  
      targetPort: 4004