apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-vidar
  name: vidar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-vidar
  template:
    metadata:
      labels:
        app: drasil-vidar
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: drasil-config
        image: docker.io/minikube/vidar:v1.3
        imagePullPolicy: Never
        name: vidar