apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-drasil-job-processor
  name: drasil-job-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-drasil-job-processor
  template:
    metadata:
      labels:
        app: drasil-drasil-job-processor
    spec:
      containers:
      - env:
        - name: CONSUMER_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podName
        envFrom:
          - configMapRef:
              name: drasil-config
        image: docker.io/minikube/drasil-jobs:v1.3
        imagePullPolicy: Never
        name: drasil-jobs