apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigg
  labels:
    app: drasil-frigg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-frigg
  template:
    metadata:
      labels:
        app: drasil-frigg
    spec:
      securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - name: frigg
        image: k3d-drasil-registry.localhost:12345/frigg:v1.3
        imagePullPolicy: IfNotPresent
        env: 
          - name: VROLE_ID
            valueFrom:
              secretKeyRef:
                name: app-vault
                key: role-id
        envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-frigg-config
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - name: dvltath
        image: k3d-drasil-registry.localhost:12345/dvltath:v1.3
        imagePullPolicy: IfNotPresent
        env: 
          - name: VROLE_ID
            valueFrom:
                secretKeyRef:
                  name: dvltath-vault
                  key: role-id
          - name: VSECRET_ID
            valueFrom:
                secretKeyRef:
                  name: dvltath-vault
                  key: role-id
        envFrom:
          - configMapRef:
              name: drasil-config
          - configMapRef:
              name: drasil-dvltath-config
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
---
# Frigg Service
apiVersion: v1
kind: Service
metadata:
  name: drasil-frigg-service
spec:
  selector:
    app: drasil-frigg
  type: LoadBalancer
  ports:
    - port: 6143
      nodePort: 30003
      protocol: TCP
      targetPort: 8000
