apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drasil-rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasil-rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drasil-rabbitmq
    spec:
      containers:
      - image: rabbitmq:latest
        imagePullPolicy: IfNotPresent
        name: rabbitmq