kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/tp/k3dvol/task-pv-volume-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/tp/k3dvol/task-pv-volume-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/tp/k3dvol/task-pv-volume-3