FROM europe-west6-docker.pkg.dev/maestro-org-development/dapp-developer-platform-base/rust:1.61.0 as maestro-rust-base

FROM maestro-rust-base as builder
WORKDIR /geri-build
ENV CARGO_HOME=/geri-build/.cargo
COPY ./Cargo.toml ./Cargo.lock ./                       
COPY ./.cargo/config $CARGO_HOME/config
COPY ./.cargo/git $CARGO_HOME/git
COPY ./src ./src
RUN cargo build --release --target x86_64-unknown-linux-gnu

FROM maestro-rust-base as geri
COPY --from=builder /geri-build/target/x86_64-unknown-linux-gnu/release/geri /usr/bin

ENV CLUSTER=false
ENV REDIS_CLUSTER=false
ENV REDIS_DB_URL_UTXOMIND="redis://default:@127.0.0.1:6379/0"
ENV REDIS_DB_URL_TXMIND="redis://default:@127.0.0.1:6379/0"
ENV STREAM_TRIMMER=true
ENV STREAMS="transaction|block"
ENV TIMEOUT=20000

CMD ["geri"]
