[package]
name = "loki"
version = "0.1.0"
edition = "2021"
description = "Drasil Blockchain Application Framework - Websocket Interface"
repository = "https://github.com/Sbcdn/drasil.git"
homepage = "https://www.drasil.io"
documentation = "https://docs.drasil.io"
license = "LICENSE.md"
readme = "README.md"
authors = ["Torben Poguntke <torben@drasil.io>"]

[dependencies]
warp = { version = "0.3", features = ["tls"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.6"
pretty_env_logger = "0.4.0"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
uuid = { version = "1.1.2", features = ["v4"] }
bincode = "1.3.3"
serde_bytes = "0.11.5"
structopt = "0.3.26"
jsonwebtoken = { version = "8.1.0", features = ["use_pem"] }
thiserror = "1.0"
bytes = "1"
futures = { version = "0.3", default-features = true }
lapin = { version = "2.1.1", features = ["rustls"] }
tokio-amqp = "2.0.0"
deadpool = "0.9.5"
deadpool-lapin = { version = "0.10.0", features = ["serde"] }
ratelimit_meter = "5.0.0"
nonzero_ext = "0.3.0"

drasil-hugin = { path = "../../drasil-hugin", version = "0.1.0" }
